import h1 from "../assets/images/popular-homes/h1.png";

export const popularHomes = [
  {
    id: 1,
    title: "Flat in Bangalore Urban",
    guestFavorite: true,
    price: 5478,
    rating: 5.0,
    image: h1,
  },
  {
    id: 2,
    title: "Flat in Bangalore Urban",
    guestFavorite: true,
    price: 5478,
    rating: 4.95,
    image: h1,
  },
  {
    id: 3,
    title: "Flat in Bangalore Urban",
    guestFavorite: true,
    price: 5478,
    image: h1,
    rating: 4.95,
  },
  {
    id: 4,
    title: "Flat in Bangalore Urban",
    guestFavorite: true,
    price: 5478,
    image: h1,
    rating: 4.95,
  },
  {
    id: 5,
    title: "Flat in Bangalore Urban",
    guestFavorite: true,
    price: 5478,
    image: h1,
    rating: 4.95,
  },
  {
    id: 6,
    title: "Flat in Bangalore Urban",
    guestFavorite: true,
    price: 5478,
    image: h1,
    rating: 4.95,
  },
  {
    id: 7,
    title: "Flat in Bangalore Urban",
    guestFavorite: true,
    price: 5478,
    image: h1,
    rating: 4.95,
  },
  {
    id: 8,
    title: "Flat in Bangalore Urban",
    guestFavorite: true,
    price: 5478,
    image: h1,
    rating: 4.95,
  },
  {
    id: 9,
    title: "Flat in Bangalore Urban",
    guestFavorite: true,
    price: 5478,
    image: h1,
    rating: 4.95,
  },
];
